name: MRI
 
on:
  push:
    branches: ["main"]
 
jobs:
  build-and-test:
    runs-on: ubuntu-latest    #[self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f req_prod.txt ]; then pip install -r req_prod.txt; fi

      - name: Lint with flake8 and PyTest
        run: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Docker Build and Push to Docker Hub
        run : |
            docker build -t mri-dl-fastapi:latest .
            docker tag mri-dl-fastapi lonewolf341/mri-dl-fastapi:latest
            docker login -u ${{ secrets.DOCKER_USERNAME  }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker push lonewolf341/mri-dl-fastapi:latest
        env:
            DOCKER_CLI_ACI: 1

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
            scan-type: 'fs'
            scan-ref: '.'
            trivy-config: trivy.yaml

      - name: Trivy File Scan
        run: |
            trivy fs . > trivy_scan.txt
            trivy image lonewolf341/mri-dl-fastapi:latest > trivy_image_scan.txt

  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run (update image only)
        run: |
          gcloud run deploy mri-dl-fastapi \
            --image=docker.io/lonewolf341/mri-dl-fastapi:latest \
            --region=us-central1 \
            --platform=managed \
            --quiet
